model:
  name: fcos
  build: build
  args:
    input_h: 592
    input_w: 800
    l2_reg: 0.00001
    dropout: 0.1
    strides:
      - 8
    regression_weight: 0.05
heads_names:
    - concatenate
    - concatenate1
ext_keys:
    - img
    - target0
data:
  train: training/train_dataset.yaml
  val: training/val_dataset.yaml
optimizer:
  name: Adam
  lr: 0.001
callbacks:
  lr_scheduler:
    factor: 0.5
    patience: 10
    cooldown: 5
  early_stop:
    patience: 25
epochs: 200
batch_size: 8